### ISSUE TITLE
where to "catkin_make"?

### ISSUE THREAD

**Issue by SharineLee** [gxytcrc/Semantic-Graph-based--global-Localization#2]
~/semantic-histogram-based-global-localization-main/build$  catkin_make

Base path: /home/sharine/semantic-histogram-based-global-localization-main/build
The specified source space "/home/sharine/semantic-histogram-based-global-localization-main/build/src" does not exist

**Comment by SharineLee** [comment]
why is there no package.xml file?

**Comment by gxytcrc** [comment]
It is not a ros package
