### ISSUE TITLE
error: expected primary-expression before ‘>’ token

### ISSUE THREAD

**Issue by SharineLee** [gxytcrc/Semantic-Graph-based--global-Localization#3]
$ cd semantic-histogram-based-global-localization-main
$ mkdir build
$ cd build
$ cmake ..
$ make

~/semantic-histogram-based-global-localization-main/src/pointCloudMapping.cpp:24:63: error: expected primary-expression before ‘>’ token
    GlobalCloud = pcl::make_shared<pcl::PointCloud<PointXYZRGB>>();
                                                                                                           
~/semantic-histogram-based-global-localization-main/src/pointCloudMapping.cpp:24:66: error: expected primary-expression before ‘)’ token
     GlobalCloud = pcl::make_shared<pcl::PointCloud<PointXYZRGB>>();

**Comment by SharineLee** [comment]
which version of pcl are you using in this project?

**Comment by gxytcrc** [comment]
maybe you can change the PCL version and try, the PCL I used is PCL 1.12.0

**Comment by SharineLee** [comment]
ok，i will try. Thanks a lot.

**Comment by SharineLee** [comment]
> maybe you can change the PCL version and try, the PCL I used is PCL 1.12.0
ok，i will try. Thanks a lot.

**Comment by SharineLee** [comment]
> maybe you can change the PCL version and try, the PCL I used is PCL 1.12.0
Thanks, the compilation is passed, it is a problem with the PCL version.

**Comment by SharineLee** [comment]
> maybe you can change the PCL version and try, the PCL I used is PCL 1.12.0

but，when i run ./mapAlignment forwardCar 0 343 backwardCar 0 300

The number of keypoint is: 3 points
Neighborhood construct
Neighborhood construct
Descriptor construct
The Neighborhood object destroyed
Descriptor construct
The Neighborhood object destroyed
matcher constructed
The Descriptor object destroyed
The Descriptor object destroyed
inlier num: 137
matching performance: 0.440514
R: 1.00012 0.00465213 0.0169056
-0.00462746 1.00005 -0.00170228
-0.0169091 0.00161751 1.00003
T: 0.012619
-3.40476
2.38978
object registration destroyed
The matching object destroyed
The Descriptor object destroyed
The Descriptor object destroyed
The Neighborhood object destroyed
The Neighborhood object destroyed

**Comment by SharineLee** [comment]
why they destroyed?

**Comment by gxytcrc** [comment]
> why they destroyed?

don't mind these lines, just the notification from the destructor
