### ISSUE TITLE
关于结果可视化

### ISSUE THREAD

**Issue by 873490374** [gxytcrc/Semantic-Graph-based--global-Localization#4]
作者您好！请问论文中Fig. 7(b)是如何得到的呢？十分感谢！

**Comment by gxytcrc** [comment]
你好，论文中图片是关于三个地图的地图融合的结果，是我调用github中的代码进行的一个可视化输出，代码中没有直接的函数可以调出这个结果，如果你需要得到这个输出的话，你需要修改下原代码，大概就是输入三个graph，保留稠密的点云，做两次文中的global localization得到Transformation matrixs， 然后应用到保留的稠密点云，最后统一输出。

**Comment by 873490374** [comment]
来信收到，祝好！

**Comment by Madaxian8** [comment]
> 

请问具体是用github中的哪个代码做的可视化输出？

**Comment by gxytcrc** [comment]
> > 
> 
> 请问具体是用github中的哪个代码做的可视化输出？

你好，可视化在pointCloudMapping::pointVisuallize函数里
